apiVersion: v2
name: app3
description: A Helm chart for deploying the Theme Park Ride Ops app3
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: common-library
    version: 1.0.0
    repository: https://charts.example.com/