apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: theme-park-ride-ops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mihrasik/theme-park-ride-ops'
    targetRevision: HEAD
    path: helm/app1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: themepark
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncWindow:
      schedule: "0 0 * * *"
      duration: 24h
  info:
    - name: Description
      value: Theme Park Ride Ops microservices application
    - name: Helm Chart
      value: app1
  # Add additional applications for app2 and app3 as needed
  # source:
  #   path: helm/app2
  # source:
  #   path: helm/app3