---
- name: Install DevOps Tools
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Remove any existing Docker packages
      apt:
        name: "{{ item }}"
        state: absent
      loop:
        - docker
        - docker-engine
        - docker.io
        - containerd.io
        - runc

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      notify:
        - Start Docker service

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Download Terraform
      get_url:
        url: "https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip"
        dest: /tmp/terraform.zip

    - name: Unarchive Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Set executable permission for Terraform
      file:
        path: /usr/local/bin/terraform
        mode: '0755'

    - name: Download k3d install script
      get_url:
        url: "https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh"
        dest: /tmp/install_k3d.sh
        mode: '0755'

    - name: Run k3d install script
      command:
        cmd: "/tmp/install_k3d.sh"
        
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Set JAVA_HOME environment variable
      lineinfile:
        path: /etc/environment
        line: JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
        create: yes

    - name: Verify JDK installation
      command: java -version
      register: java_version
      changed_when: false

    - name: Display Java version
      debug:
        msg: "Java version: {{ java_version.stdout }}"
  handlers:
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
