/theme-park-ride-ops/theme-park-ride-ops/helm/charts/service3/Chart.yaml
apiVersion: v2
name: service3
description: A Helm chart for Kubernetes deployment of Service 3
type: application
version: 0.1.0
appVersion: "1.0"