apiVersion: v1
kind: Service
metadata:
  name: ride-ops
  namespace: themepark-app
spec:
  selector:
    app: ride-ops
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: ClusterIP