theme-park-ride-ops/theme-park-ride-ops/helm/charts/app1/Chart.yaml
apiVersion: v2
name: app1
description: A Helm chart for Kubernetes deployment of app1
type: application
version: 0.1.0
appVersion: "1.0"
dependencies: []