/theme-park-ride-ops/theme-park-ride-ops/helm/charts/app2/Chart.yaml
apiVersion: v2
name: app2
description: A Helm chart for deploying app2
type: application
version: 0.1.0
appVersion: "1.0"
dependencies: []