/theme-park-ride-ops/theme-park-ride-ops/helm/charts/service1/Chart.yaml
apiVersion: v2
name: service1
description: A Helm chart for Kubernetes to deploy service1
type: application
version: 0.1.0
appVersion: "1.0"