helm/subcharts/app-chart/Chart.yaml
apiVersion: v2
name: app-chart
description: A Helm chart for deploying the ride-ops application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: db-chart
    version: 0.1.0
    repository: file://../db-chart