helm/subcharts/app-chart/values.yaml
# This file contains default configuration values for the app subchart.

replicaCount: 3

image:
  repository: ${REGISTRY_URL}/ride-ops-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: true
  name: ride-ops-api
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}

ingress:
  enabled: false
  name: ""
  path: /
  pathType: ImplementationSpecific
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []  # Treated as an array of objects

resources: {}
# Requests and limits for CPU and memory can be specified here

nodeSelector: {}

tolerations: []

affinity: {}