# /k8s/app/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: themepark-ingress
  namespace: themepark-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: rideops.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ride-ops-service
                port:
                  number: 8080
    - host: rideops-ui.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ride-ops-ui-service
                port:
                  number: 80