# templates/db.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetPort }}
  selector:
    app: {{ .Release.Name }}-mariadb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Values.namespace }}
spec:
  serviceName: {{ .Release.Name }}-mariadb
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mariadb
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mariadb
    spec:
      containers:
        - name: mariadb
          image: {{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.db.database }}
            - name: MYSQL_USER
              value: {{ .Values.db.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mariadb-secret
                  key: mysql-password
          ports:
            - containerPort: {{ .Values.db.service.targetPort }}
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-mariadb-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mariadb-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - {{ .Values.db.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.db.pvc.size }}