apiVersion: v1
appVersion: "1.0"
description: A Helm chart for deploying App2
name: app2
version: 0.1.0

# Default values for App2
replicaCount: 1

image:
  repository: your-docker-repo/app2
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  enabled: true
  name: app2
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}

ingress:
  enabled: false
  name: ""
  pathType: ImplementationSpecific
  path: /
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []  # Treated as an array of objects

resources: {}
# Limits and requests for CPU and memory can be specified here

nodeSelector: {}

tolerations: []

affinity: {}