/theme-park-ride-ops/theme-park-ride-ops/helm/charts/mariadb/Chart.yaml
apiVersion: v2
name: mariadb
description: A Helm chart for Kubernetes to deploy MariaDB
type: application
version: 1.0.0
appVersion: "10.5"