helm/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: themepark-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  db_user: {{ .Values.db.user | b64enc | quote }}
  db_password: {{ .Values.db.password | b64enc | quote }}