apiVersion: v1
kind: ConfigMap
metadata:
  name: app3-config
  namespace: themepark
data:
  application.properties: |
    spring.datasource.url=jdbc:mariadb://mariadb:3306/themepark
    spring.datasource.username=${DB_USERNAME}
    spring.datasource.password=${DB_PASSWORD}
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
    server.port=8083

replicaCount: 2

image:
  repository: your-dockerhub-username/app3
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 8083

ingress:
  enabled: true
  path: /
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: app3.themepark.local
      paths:
        - /

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}