/theme-park-ride-ops/theme-park-ride-ops/helm/umbrella-chart/Chart.yaml
apiVersion: v2
name: theme-park-ride-ops
description: A Helm chart for deploying the Theme Park Ride Ops application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: app-chart
    version: 0.1.0
    repository: file://../subcharts/app-chart
  - name: db-chart
    version: 0.1.0
    repository: file://../subcharts/db-chart