apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app1
  labels:
    app: {{ .Release.Name }}-app1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app1
    spec:
      containers:
        - name: app1
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.springProfile }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}